#!/usr/bin/env python3
import sys
import autosync_extras


def help(var_name):
	print(autosync_extras.__dict__[var_name.upper()])
	sys.exit()


def autosync():
	args = [s.lower() for s in sys.argv]
	if len(args) == 1 or args[1] == "help":
		help("help_root")

	fun = args[1]

	if fun == "about":
		help("about")

	if fun == "status":
		print("This is a status")

	if fun == "add":
		if len(args) == 2 or args[2] == "help":
			help("help_add")



if __name__ == '__main__':
	autosync()